name: Test

on:
  push:
    branches:
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          cd backend
          npm ci --legacy-peer-deps
      - name: Run tests
        run: |
          cd backend
          npm test
